openapi: 3.0.3
info:
  title: 台北榮總 Roche Cancer FHIR Converter- API 使用說明書
  description: |-
    台北榮總 Roche Cancer FHIR Converter :

            API 0.1.0 based on the OpenAPI 3.0 specification.

    概述 : 

            將癌症病例轉成FHIR 並存入Roche DPI
            

    對象 :

            門診病歷
            
    方法 : 
            
            依Roche Fhir標準，將欄位對應至FHIR相對resourceType欄位，存入DPI

    配套 : 

            True 無法處理 需改成 true
            None 無法處理 需改成 ""

    注意事項 :
    
            1.Request body 內 Example Value 與 Schema 僅為說明格式，section 及 entry 重複格式不逐一說明，詳細說明請參照範例資料註解
            2.測試時請由下方連結下載範例資料複製貼上至 Request body 內 Example Value 執行
            3.後續維護更新責任者-緯謙科技

    Some useful links:
    - [癌症病例json測試patient資料](/Patient)
    - [專案負責部門 : T02300 ]
    - [電話 : 02-66126262]
    - [分機 : 14711 ]

    - [Roche FHIR Converter](http://104.208.68.39:8200)

  contact:
    email: Gojim.Yu@wiadvance.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: Find out more about 緯謙科技
  url: https://www.wiadvance.com/
servers:
  - url: http://104.208.68.39:8100
    description: VGHTPE Roche FHIR Converter

paths:
  /:
    get:
      tags:
        - Server
      summary: 回傳伺服器狀態
      description: 回傳伺服器狀態

      operationId: getInventory
      parameters: []
      responses:
        '200':
          description: "Server Status : run (正常)"
        '500':
          description: "internal server error (內部伺服器錯誤)"
          

  /RocheCancerBundle/:
    post:
      tags:
        - 癌症病歷
      summary: 上傳癌症病歷
      description: 上傳癌症病歷資料
      operationId: RocheCancerBundle
      requestBody:
        description: Composition_VisitNote
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
        required: true
      responses:
        '202':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'



        
components:
  schemas:
    Composition_VisitNote_ApiResponse_JSON:
      type: object
      properties:
        resourceType:
          type: string
        id:
          type: string
        meta:
          type: object
          properties:
            versionId:
              type: string
            lastUpdated:
              type: string
            source:
              type: string
        language:
          type: string
        text:
          type: object
          properties:
            status:
              type: string
            div:
              type: string
        status:
          type: string
        type:
          type: object
          properties:
            coding:
              type: object
              properties:
                system:
                  type: string
                code:
                  type: string
                display:
                  type: string
        subject:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        encounter:
          type: object
          properties:
            reference:
              type: string
        date:
          type: string
        author:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        title:
          type: string
        confidentiality:
          type: string
        attester:
          type: object
          properties:
            mode:
              type: string
            time:
              type: string
        custodian:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        section:
          type: object
          properties:
            title:
              type: string
            code:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string
            text:
              type: object
              properties:
                status:
                  type: string
                div:
                  type: string
            entry:
              type: object
              properties:
                reference:
                  type: string
      example:
        resourceType: "Bundle"
        identifier: 
            use: "official"
            type: 
              coding: [
                {
                  "system": "https://dip.roche.com/context-codesystem/impacted-any/assigner-dip/identifier-type",
                  "code": "bundleId",
                  "display": "Bundle Identifier"
                }
              ]
            system: "https://dip.roche.com/context-identifier/impacted-bundle-identifier/assigner-vghtpe/identifier-vghtpe"
            value: "637cbf21-2844-475d-9d80-7a1985999a6b"
        type: "message"
        timestamp: "2021-05-13T08:56:38.1069161+08:00"
        entry: [
          {
            "link": [
              {
                "relation": "type",
                "url": "https://dip.roche.com/entryclassifier?type=90090-2"
              },
              {
                "relation": "profile",
                "url": "https://dip.roche.com/context-identifier/impacted-Bundle-entry/modeProfile/snapshot"
              }
            ],
            "fullUrl": "urn:uuid:a9d65168-07fc-4e59-b340-e21abafd7789",
            "resource": {
              "resourceType": "MessageHeader",
              "id": "a9d65168-07fc-4e59-b340-e21abafd7789",
              "text": {
                "status": "generated",
                "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">MessageHeader</div>"
              },
              "extension": [
                {
                  "url": "https://DIP.roche.com/context-extensions/impacted-MessageHeader/x_MessageSubjectIdentifier",
                  "valueIdentifier": {
                    "use": "official",
                    "type": {
                      "coding": [
                        {
                          "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                          "code": "MR",
                          "display": "Medical Record Number"
                        }
                      ]
                    },
                    "system": "http://www.vghtpe.org.tw/fhir/patient-identifier",
                    "value": "98765436"
                  }
                },
                {
                  "url": "https://dip.roche.com/context-extensions/impacted-MessageHeader/x_MessageTimestamp",
                  "valueDateTime": "2021-05-13T08:56:38.1099212+08:00"
                }
              ],
              "eventCoding": {
                "system": "https://hl7.org/fhir/message-events",
                "code": "communication-request",
                "display": "communication-request"
              },
              "source": {
                "name": "vghtpe Interface Engine",
                "software": "HAPI",
                "version": "5.2.0",
                "endpoint": "EnterEndPOintHere"
              }
            }
          },
          {
            "link": [
              {
                "relation": "type",
                "url": "https://dip.roche.com/entryclassifier?type=79191-3"
              },
              {
                "relation": "profile",
                "url": "https://dip.roche.com/context-identifier/impacted-Bundle-entry/modeProfile/snapshot"
              }
            ],
            "fullUrl": "urn:uuid:86792f98-e4f6-4a71-9a04-a962fb759210",
            "resource": {
              "resourceType": "Patient",
              "id": "86792f98-e4f6-4a71-9a04-a962fb759210",
              "identifier": [
                {
                  "type": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR"
                      }
                    ]
                  },
                  "system": "http://www.vghtpe.org.tw/fhir/patient-identifier",
                  "value": "98765436"
                }
              ],
              "active": true,
              "name": [
                {
                  "family": "朱O嘉",
                  "given": [
                    "朱O嘉"
                  ]
                }
              ],
              "gender": "male",
              "birthDate": "1980-06-01",
              "telecom": [
                {
                  "rank": 1,
                  "value": "23222111",
                  "system": "phone"
                },
                {
                  "rank": 2,
                  "system": "phone"
                }
              ],
              "address": [
                {
                  "text": "臺北市士林區社子街１６０號４樓",
                  "type": "physical",
                  "postalCode": "111"
                }
              ]
            }
          }
        ]


  securitySchemes:
    wiadvance_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://www.wiadvance.com/oauth/authorize
          scopes:
            put:VisitNote: 更新門診病例
            delete:VisitNote: 刪除門診病例
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_petstore_auth
      x-scopeValidateFunc: >-
        swagger_server.controllers.authorization_controller.validate_scope_petstore_auth
    api_key:
      type: apiKey
      name: api_key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key
